### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by RIKR6735** [sirodeneko/jsbilibiliDanmu#1]
1自定义字幕颜色大小位置
2可拖动、缩放字幕
3可自定义同传man
4可视化配置界面
5自动去括号

**Comment by sirodeneko** [comment]
1. 字幕样式可以在代码里定义，已经加以说明了
2. 本人太菜，一时半会搞不定
3. 这个感觉没必要，很少出现多个同传man吧
4. 这。。。下次一定（咕咕咕）
5. 已修改（其实感觉有括号舒服点）
6. 谢谢您的star /狗头

**Comment by RIKR6735** [comment]
我觉得第三个还是很有用的，因为有时候有大量野生同传导致翻译质量参差不齐（个别人气v）翻译速度上也有一定差距，而且也有观众随意用括号，然后出现一些意义不名的评论翻译，所以自定义同传还是挺有用的
