### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by yinchao-qaq** [sirodeneko/jsbilibiliDanmu#2]
一、字幕允许使用rgb颜色或者十六进制颜色，16种颜色名局限太大了，常常没有合适、与背景画面区分度高的颜色
二、字幕加深色边（就像弹幕那种的一样） 没有的话与背景区分度太低 常常看不清

**Comment by yinchao-qaq** [comment]
好快的修改速度

**Comment by sirodeneko** [comment]
啊这。。。你满意就好
