### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by czm888** [sirodeneko/jsbilibiliDanmu#3]
我在
zimuColor="#FFFFFF";//修改此处改变字幕颜色
var zimuShadowColor="#66CCFF"// 弹幕阴影颜色
进行了修改，将颜色替换成了我自己喜欢的颜色，但是进入直播间之后显示的并非我设置的颜色，需要点击左上角“字幕设置”点一次确定之后才会变成设置的颜色。请问是哪里搞错了吗？

**Comment by sirodeneko** [comment]
1. 修改后是否保存了
2. 是否自动更新了新脚本,导致新脚本覆盖了你的修改
3. 页面是否刷新（脚本要刷新页面才能更新）

**Comment by czm888** [comment]
1.保存我还是知道的
2.我是新添加的脚本，油猴的自动更新也是关着的，所以内容并没有被修改
3.这样说吧，我是修改了，Ctrl+S，重新进入直播间，然后并非我设置的颜色（刚才又检查了一遍，主要是阴影颜色不是我改的那个），点出“字幕设置”直接点确定按钮一次之后就是我要那个了（字幕设置里显示的是我要那个颜色），然后刷新或者跑别的直播间阴影又变了。

**Comment by sirodeneko** [comment]
将 62行改成113行这个样子😥

**Comment by czm888** [comment]
😥解决啦。谢谢！
