### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by LS2233** [sirodeneko/jsbilibiliDanmu#4]
B站网页直播还有全屏和网页全屏，我个人喜欢把字幕放在屏幕上方，设置好字幕的位置之后进入网页全屏模式之后字幕的位置会跑到视频中间，而且在全屏模式下字幕无法显示。还有就是希望作者出一个新字幕出现现在旧字幕的下方的选项，谢谢。

**Comment by sirodeneko** [comment]
全屏模式 无解。。。技术力不够
网页全屏可以试试
已经更新了
![image](https://user-images.githubusercontent.com/48661001/116407632-8b2b5180-a864-11eb-8128-9c463a1c7188.png)
这个高度大概为600差不多就是在顶上了。

目前 就是新字幕出现现在旧字幕的下方啊

**Comment by LS2233** [comment]
更新后试了一下：我屏幕是1920*1080的。
直播间正常模式下字幕高度设置为560时字幕在屏幕上方


然后切换为网页全屏模式之后字幕位置在屏幕中间偏上而且偏左

网页全屏设置为810时在屏幕上方


切换成正常模式后字幕位置超出屏幕高度无法显示

新字幕出现现在旧字幕的下方这个问题时我的锅&nbsp; 描述错了。
现在出现新字幕的时候新字幕会顶替旧字幕的位置，旧字幕向上位移，如果字幕设置在屏幕下方会很正常，但是设置在上方时就会出现问题。

在上方时应该让新字幕直接出现在，旧字幕下方。
啊 看着都麻烦&nbsp; 再次感谢大佬



-----------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sirodeneko/jsbilibiliDanmu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sirodeneko/jsbilibiliDanmu] 一些小问题 (#4)





 
全屏模式 无解。。。技术力不够
 网页全屏可以试试
 已经更新了
 
 这个高度大概为600差不多就是在顶上了。
 
目前 就是新字幕出现现在旧字幕的下方啊

**Comment by sirodeneko** [comment]
又更了一版，试试？

**Comment by LS2233** [comment]
已经试了，一切正常，辛苦了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sirodeneko/jsbilibiliDanmu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 晚上10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sirodeneko/jsbilibiliDanmu] 一些小问题 (#4)





 
又更了一版，试试？
